### ISSUE TITLE
PDQ: Standard ISO/IEC 9126

### ISSUE THREAD

**Issue by Jatus93** [TennersUnipd/sweDocs#32]
Come abbiamo intenzione di seguire le linee guida presenti in ISO/IEC 9126

**Comment by giovanni9793** [comment]
Dato che lo standard 9126 é stato rivisto in quello 25010 (secondo [iso.org](https://www.iso.org/standard/22749.html) che raccoglie i vari standard), il nuovo standard usato sarà il 25010
