### ISSUE TITLE
Revisione struttura PDQ

### ISSUE THREAD

**Issue by giovanni9793** [TennersUnipd/sweDocs#36]
Al momento la struttura del Piano di Qualifica é la seguente:

#26)Sezione Introduttiva
#27)Visione generale della strategia di gestione della qualità:
-(#28)Obiettivi della qualità
-(#29)Scadenze temporali che intendiamo seguire
#30)Strategia di gestione della qualità nel dettaglio
#31)Capability Maturity Model (way of working)
#32)Standard ISO/IEC 9126 (qualità del software)
#33)PDCA(Plan Do Check Act) Implementazione di ISO 9001
#34)Come gestiremo la parte di sviluppo dei test

Mentre io proporrei una struttura di questo tipo (cosa fare con riferimenti esterni, test):

#26)Sezione Introduttiva
#27)Visione generale della strategia di gestione della qualità:
-(#28)Obiettivi della qualità
-(#29)Scadenze temporali che intendiamo seguire
#30)Strategia di gestione della qualità nel dettaglio
#32)Standard ISO/IEC 9126 (qualità del software)
#31)Capability Maturity Model (way of working)
#33)PDCA(Plan Do Check Act) Implementazione di ISO 9001
#34)Come gestiremo la parte di sviluppo dei test

O di questo tipo (cosa fare, test, riferimenti esterni):

#26)Sezione Introduttiva
#27)Visione generale della strategia di gestione della qualità:
-(#28)Obiettivi della qualità
-(#29)Scadenze temporali che intendiamo seguire
#30)Strategia di gestione della qualità nel dettaglio
#31)Capability Maturity Model (way of working)
#34)Come gestiremo la parte di sviluppo dei test
#32)Standard ISO/IEC 9126 (qualità del software)
#33)PDCA(Plan Do Check Act) Implementazione di ISO 9001

**Comment by Jatus93** [comment]
Approvata la terza versione
