### ISSUE TITLE
Modifiche Piano di qualifica

### ISSUE THREAD

**Issue by Jatus93** [TennersUnipd/sweDocs#64]
- [x] Spostare lo standard 9126 in riferimento informativo

- [x] rivedere l'uso del 12207

- [x] Spostare la descrizione delle metriche di qualità del software in NDP

- [x] Snellire colonna descrizione per l'appendice TA

- [x] esiti delle modifiche con un grafico dell'andamento

**Comment by giovanni9793** [comment]
Fatto
