### ISSUE TITLE
PdP Preventi e Consunti di Periodo

### ISSUE THREAD

**Issue by salvanicola** [TennersUnipd/sweDocs#99]

**Comment by gcikaqi** [comment]
Bisogna sistemare le tabelle:

Tabella 6.3.2: Tabella ore e costo totale previsti per incremento, progettazione di dettaglio e codifica (andrà messa sotto la tabella Tabella 6.3.1)

Tabella 6.3.3: Tabella preventivo a finire (e questo invece va messo nel paragrafo 6.3.2 Preventivo a finire
)
